# Generated by Django 5.2.15 on 2026-06-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=255)),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('resultats_ssl', models.JSONField(default=dict)),
                ('score_risque_ia', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_pdf', models.CharField(max_length=500)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cvss_score', models.FloatField(default=0.0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cves', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='scanner.scan')),
            ],
        ),
    ]
